image:
  file: .gitpod.Dockerfile
  context: scripts
vscode:
  extensions:
    - mauve.terraform@1.4.0:27r9VdcnEIBpa1jdjPSXdA==
tasks:
  - command: |
      read -p "Do you want to deploy (y/n)? " deploy
      if [ $deploy = y ]; then
        scripts/install-gitpod.sh
      fi
  - command: echo ''
    openMode: split-right
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
