image:
  file: .gitpod.Dockerfile
  context: scripts
vscode:
  extensions:
    - mauve.terraform@1.4.0:27r9VdcnEIBpa1jdjPSXdA==
tasks:
  - command: |
      cd src
      terraform init
      terraform apply -var-file dev.tfvars
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
