image:
  file: .gitpod.Dockerfile
  context: scripts
vscode:
  extensions:
    - mauve.terraform@1.4.0:27r9VdcnEIBpa1jdjPSXdA==
tasks:
  - init: |
      cd src
      git clone "git://github.com/gitpod-io/self-hosted"
      mv *.tf self-hosted
      cd self-hosted
      terraform init
      terraform apply
